Features/add filter challenge by level and by techs
Lorenalgm/DevChallengeAPI pull request #24
Opened 2020-12-26 20:29 UTC by BrunoBatalha

Estou adicionando +2 filtros para a listagem de desafios (_challenges_).

Percebi que no FrontEnd (https://devchallenge.com.br/challenges) há uma opção de filtrar os desafios (_challenges_) por categoria (_type_) e linguagem (_techs_), mas em um momento pensei em filtrar por dificuldade, mas não havia esta opção, também vi que o filtro de tecnologias (_techs_) não estava funcionando, e então como uma maneira de facilitar a busca de desafios (_challenges_) para outros devs, implementei na API estes filtros.

**Check-list:**
- [ ] A Pull Request soluciona uma issue.
- [ ] Executar `npm run test` passará todos as suítes de testes definidas (Incluindo lint).
- [ ] Adicionei novos testes para previnir falhas.
- [X] Atualizei a documentação de acordo com as alterações no código (Se aplicável).
- [X] Li e segui o [guia de contribuição](https://github.com/Lorenalgm/DevChallengeAPI/blob/master/CONTRIBUTING.md) disponibilizado.

2020-12-28 11:21 UTC, ramos-ph commented
Muito obrigado pela contribuição!

Percebi que a branch `develop` está destualizada em relação à documentação da `master`. Vou fazer um merge e corrigir os conflitos.

2020-12-28 11:30 UTC, ramos-ph commented
Acabei de fazer o merge da `master` na branch `develop`. Poderia corrigir alguns conflitos, @BrunoBatalha ?

2020-12-28 11:41 UTC, BrunoBatalha commented
Acabei de resolver @ramos-ph

2020-12-28 12:20 UTC, ramos-ph requested changes
No geral está ótimo, mas poderia mover essa lógica de filtro para o `challengeService`?

2020-12-28 12:30 UTC, BrunoBatalha commented
Ah sim, agr que entendi direito, vou fazer

2020-12-31 04:37 UTC, BrunoBatalha commented
Lógica movida @ramos-ph

2020-12-31 14:46 UTC, ramos-ph commented on src/services/challenges.service.js
> +    Object.keys(queryString).map(property => {
Se não vai retornar nada, seria melhor utilizar um `forEach` ao invés do `map`

2020-12-31 14:54 UTC, ramos-ph reviewed
As alterações estão muito bem feitas!

Meu único pedido mesmo é o que comentei sobre o `.map`.

Detalhes de implementação podemos alterar depois.

2020-12-31 14:54 UTC, ramos-ph commented on src/services/challenges.service.js
> +    Object.keys(queryString).map(property => {
Se não está retornando nada, seria melhor utilizar um `.forEach` ao invés do `.map` :smile:

2020-12-31 14:54 UTC, ramos-ph commented on src/services/challenges.service.js
> +    });
Poderia extrair isso para uma função privada dentro do arquivo que retorna o filtro já pronto. Por exemplo: `getFilters`. Mas isso é detalhe de implementação.

2020-12-31 14:54 UTC, ramos-ph commented on src/services/challenges.service.js
> +    });
Também olhando essa função, me parece que isso poderia ser substituido por um `.reduce` pra manter a imutabilidade. Mas, novamente, é detalhe de implementação.

2020-12-31 14:55 UTC, ramos-ph commented
@stevescruz pode dar uma olhada?

2020-12-31 18:16 UTC, BrunoBatalha commented
Detalhes de implementação resolvidos

2020-12-31 18:19 UTC, ramos-ph approved these changes
LGTM!

2020-12-31 18:20 UTC, merged

2020-12-31 18:20 UTC, ramos-ph commented
Muito obrigado por sua contribuição!

2021-01-03 05:08 UTC, stevescruz reviewed
It also LGTM.